name: Generate Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # 只在文件变更时触发
    paths:
      - "**.xmind"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set node version to 18.20.3
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Run Script
        run: pnpm install && pnpm generateReadme && pnpm prettier

      - name: Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: main
          commit-message: "Update README.md by Github Actions"
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
